name: Release

# Controls when the action will run.
on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build-release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write release version
        run: |
          TAG=${{github.ref_name}}
          echo "VERSION=${TAG:1}" >> $GITHUB_ENV

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install clojure cli
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.12.0.1530

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Jar
        run: clojure -T:build jar :version \"${VERSION}\"

      - name: Deploy on clojars
        run: clojure -T:build deploy :version \"${VERSION}\"
        env:
          CLOJARS_USERNAME: ${{ vars.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
